import { type Locator, type Page } from '@playwright/test'

// What the New Unit Type grid row needs. The name is supplied as a prefix so that
// every run creates a distinguishable unit type; the unique suffix is generated by
// the page object that submits the form rather than stored. The two category
// fields name a ledger item type and are picked from an autocomplete, so their
// values differ per environment.
export type UnitTypeFormData = {
  namePrefix: string
  description: string
  bedrooms: string
  bathrooms: string
  marketRent: string
  rentCategory: string
  requiredDeposit: string
  depositCategory: string
  squareFootage: string
  maximumOccupancy: string
}

export class NewUnitTypePage {
  // The form's own property box, pre-filled from the BoardRoom selection. A third
  // authored id for the same concept — the form uses #PropertyName where the list
  // uses #PropertyIDInput.
  public readonly propertySelector: Locator
  public readonly addButton: Locator
  public readonly saveButton: Locator
  // Inputs are named UnitTypes[<generated row guid>].<field>, so each field is
  // reached through its stable name suffix rather than the generated id.
  public readonly nameInput: Locator
  public readonly descriptionInput: Locator
  public readonly bedroomsInput: Locator
  public readonly bathroomsInput: Locator
  public readonly marketRentInput: Locator
  public readonly requiredDepositInput: Locator
  public readonly squareFootageInput: Locator
  public readonly maximumOccupancyInput: Locator
  // Both Category columns are autocompletes over a hidden <select>; the visible
  // input is the select's id with an "Input" suffix and carries no label.
  public readonly rentCategoryInput: Locator
  public readonly depositCategoryInput: Locator

  constructor(private page: Page) {
    this.propertySelector = this.page.locator('#PropertyName')
    this.addButton = this.page.getByRole('button', { name: 'Add' })
    this.saveButton = this.page.getByRole('button', { name: 'Save' })
    this.nameInput = this.page.locator('input[name$=".Name"]')
    this.descriptionInput = this.page.locator('input[name$=".Description"]')
    this.bedroomsInput = this.page.locator('input[name$=".Bedrooms"]')
    this.bathroomsInput = this.page.locator('input[name$=".Bathrooms"]')
    this.marketRentInput = this.page.locator('input[name$=".MarketRent"]')
    this.requiredDepositInput = this.page.locator('input[name$=".RequiredDeposit"]')
    this.squareFootageInput = this.page.locator('input[name$=".SquareFootage"]')
    this.maximumOccupancyInput = this.page.locator('input[name$=".MaximumOccupancy"]')
    this.rentCategoryInput = this.page.locator('input[name$="RentLedgerItemTypeIDInput"]')
    this.depositCategoryInput = this.page.locator('input[name$="DepositLedgerItemTypeIDInput"]')
  }

  // Parametrized by a category read from the data store. Only the open
  // autocomplete's list is in the accessibility tree, so the menu item needs no
  // parent scope — but it does need an exact name: the ledger item types include
  // pairs like "Auto Rent Charge" and "Non Auto Rent charge" that a substring
  // match would both resolve.
  categorySuggestion(category: string): Locator {
    return this.page.getByRole('menuitem', { name: category, exact: true })
  }

  // Returns the name it created, so the caller can identify the new unit type.
  async addUnitType(unitType: UnitTypeFormData): Promise<string> {
    const name = `${unitType.namePrefix}${Math.random().toString(36).slice(2, 8)}`

    // "Add" appends one inline editable row; the fills below auto-wait for that
    // row's inputs to appear, so no explicit wait is needed between them.
    await this.addButton.click()
    await this.nameInput.fill(name)
    await this.descriptionInput.fill(unitType.description)
    await this.bedroomsInput.fill(unitType.bedrooms)
    await this.bathroomsInput.fill(unitType.bathrooms)
    await this.marketRentInput.fill(unitType.marketRent)
    await this.chooseCategory(this.rentCategoryInput, unitType.rentCategory)
    await this.requiredDepositInput.fill(unitType.requiredDeposit)
    await this.chooseCategory(this.depositCategoryInput, unitType.depositCategory)
    await this.squareFootageInput.fill(unitType.squareFootage)
    await this.maximumOccupancyInput.fill(unitType.maximumOccupancy)
    await this.saveButton.click()

    return name
  }

  // Private, and parametrized by the field it drives: the Rent and Deposit
  // category columns are the same widget, so one helper serves both rather than
  // two methods differing only in which input they target.
  private async chooseCategory(categoryInput: Locator, category: string) {
    // fill() sets the value without keystrokes, which never opens the suggestions.
    await categoryInput.pressSequentially(category)
    await this.categorySuggestion(category).click()
  }
}
