import { type Locator, type Page } from '@playwright/test'

// What the New Unit Type grid row needs. The name is supplied as a prefix so that
// every run creates a distinguishable unit type; the unique suffix is generated by
// the page object that submits the form rather than stored. The two category
// fields name a ledger item type and are picked from an autocomplete, so their
// values differ per environment.
export type UnitTypeFormData = {
  namePrefix: string
  description: string
  bedrooms: string
  bathrooms: string
  marketRent: string
  rentCategory: string
  requiredDeposit: string
  depositCategory: string
  squareFootage: string
  maximumOccupancy: string
}

export class NewUnitTypePage {
  // The form's own property box, pre-filled from the BoardRoom selection. A third
  // authored id for the same concept — the form uses #PropertyName where the list
  // uses #PropertyIDInput.
  public readonly propertySelector: Locator
  public readonly addButton: Locator
  public readonly saveButton: Locator
  // Inputs are named UnitTypes[<generated row guid>].<field>, so each field is
  // reached through its stable name suffix rather than the generated id. Each is
  // plural and matches one element per grid row; methods pick the row by index
  // (see the inline-grid rule in playwright-scripting.md).
  public readonly nameInputs: Locator
  public readonly descriptionInputs: Locator
  public readonly bedroomsInputs: Locator
  public readonly bathroomsInputs: Locator
  public readonly marketRentInputs: Locator
  public readonly requiredDepositInputs: Locator
  public readonly squareFootageInputs: Locator
  public readonly maximumOccupancyInputs: Locator
  // Both Category columns are autocompletes over a hidden <select>; the visible
  // input is the select's id with an "Input" suffix and carries no label.
  public readonly rentCategoryInputs: Locator
  public readonly depositCategoryInputs: Locator

  constructor(private page: Page) {
    this.propertySelector = this.page.locator('#PropertyName')
    // Exact: the grid toolbar also carries "Copy", and a substring match is one
    // "Add Row" away from being ambiguous.
    this.addButton = this.page.getByRole('button', { name: 'Add', exact: true })
    this.saveButton = this.page.getByRole('button', { name: 'Save', exact: true })
    this.nameInputs = this.page.locator('input[name$=".Name"]')
    this.descriptionInputs = this.page.locator('input[name$=".Description"]')
    this.bedroomsInputs = this.page.locator('input[name$=".Bedrooms"]')
    this.bathroomsInputs = this.page.locator('input[name$=".Bathrooms"]')
    this.marketRentInputs = this.page.locator('input[name$=".MarketRent"]')
    this.requiredDepositInputs = this.page.locator('input[name$=".RequiredDeposit"]')
    this.squareFootageInputs = this.page.locator('input[name$=".SquareFootage"]')
    this.maximumOccupancyInputs = this.page.locator('input[name$=".MaximumOccupancy"]')
    this.rentCategoryInputs = this.page.locator('input[name$="RentLedgerItemTypeIDInput"]')
    this.depositCategoryInputs = this.page.locator('input[name$="DepositLedgerItemTypeIDInput"]')
  }

  // Parametrized by a category read from the data store. Only the open
  // autocomplete's list is in the accessibility tree, so the menu item needs no
  // parent scope — but it does need an exact name: the ledger item types include
  // pairs like "Auto Rent Charge" and "Non Auto Rent charge" that a substring
  // match would both resolve.
  categorySuggestion(category: string): Locator {
    return this.page.getByRole('menuitem', { name: category, exact: true })
  }

  // The banner reports the outcome of this form's submit, so it is owned here even
  // though saving returns to the list and the banner renders there. Parametrized by
  // the number of rows saved, so it cannot be a constructor property.
  unitTypesAddedMessage(count: number): Locator {
    return this.page.getByRole('cell', { name: `${count} unit type(s) added successfully!` })
  }

  // Builds `unitTypeCount` rows and saves them in one submit, so the confirmation
  // the caller asserts on counts exactly the rows filled here. Returns the names it
  // created, so the caller can identify the new unit types.
  async addUnitTypes(unitType: UnitTypeFormData, unitTypeCount: number): Promise<string[]> {
    const unitTypeNames: string[] = []

    for (let index = 0; index < unitTypeCount; index++) {
      const name = `${unitType.namePrefix}${Math.random().toString(36).slice(2, 8)}`

      // "Add" appends one inline editable row at the end of the grid, so this
      // iteration owns row `index`. Addressing it by index is what makes the fill
      // wait for the new row: until the grid appends it, nth(index) matches
      // nothing and the action keeps polling rather than filling the row before.
      await this.addButton.click()
      await this.nameInputs.nth(index).fill(name)
      await this.descriptionInputs.nth(index).fill(unitType.description)
      await this.bedroomsInputs.nth(index).fill(unitType.bedrooms)
      await this.bathroomsInputs.nth(index).fill(unitType.bathrooms)
      await this.marketRentInputs.nth(index).fill(unitType.marketRent)
      await this.chooseCategory(this.rentCategoryInputs.nth(index), unitType.rentCategory)
      await this.requiredDepositInputs.nth(index).fill(unitType.requiredDeposit)
      await this.chooseCategory(this.depositCategoryInputs.nth(index), unitType.depositCategory)
      await this.squareFootageInputs.nth(index).fill(unitType.squareFootage)
      await this.maximumOccupancyInputs.nth(index).fill(unitType.maximumOccupancy)

      unitTypeNames.push(name)
    }

    await this.saveButton.click()

    return unitTypeNames
  }

  // Private, and parametrized by the field it drives: the Rent and Deposit
  // category columns are the same widget, so one helper serves both rather than
  // two methods differing only in which input they target.
  private async chooseCategory(categoryInput: Locator, category: string) {
    // fill() sets the value without keystrokes, which never opens the suggestions.
    await categoryInput.pressSequentially(category)
    await this.categorySuggestion(category).click()
  }
}
