import { randomUUID } from 'crypto'
import { type APIRequestContext, type APIResponse } from '@playwright/test'
import { decodeHtmlEntities, optionValueByText } from '../../helpers/html-form'

// What the New Building endpoint needs for one building. The name is supplied as a
// prefix: the application caps it at 15 characters and rejects duplicates ("This building
// already exists"), so the unique suffix is generated by the client that submits the form
// rather than stored in the data — the same split the New Building page object makes.
export type BuildingApiData = {
  namePrefix: string
  floors: string
  description: string
  streetAddress: string
  city: string
  province: string
  postalCode: string
}

// What the save produced: the name it generated, and the response it produced, so the
// spec asserts on the save itself rather than trusting a method that returned normally.
export type CreatedBuilding = {
  name: string
  saveResponse: APIResponse
}

// One row of the Buildings list, as the application lists it back.
export type ListedBuilding = {
  name: string
  floors: string
  description: string
}

// The application's own client sends this on every module request, and the controllers
// answer a request without it with the full application shell instead of the partial the
// endpoint is documented — by observation — to return.
const AJAX_HEADERS = { 'X-Requested-With': 'XMLHttpRequest' }

// The pager's "All" link is page 0, so one request returns every building on the
// property instead of walking 25 rows at a time.
const ALL_PAGES = '0'

// The text of one cell of a list row, tags stripped. Scoped to the row the caller
// already isolated: matching a cell against the whole list document would run a lazy
// match across the row boundary and read the next building's values.
function cellText(rowHtml: string, columnClass: string): string {
  const cell = rowHtml.match(new RegExp(`<td class="${columnClass}">([\\s\\S]*?)</td>`, 'i'))

  return cell ? decodeHtmlEntities(cell[1].replace(/<[^>]*>/g, '')).trim() : ''
}

export class BuildingsApi {
  constructor(private request: APIRequestContext) {}

  // The id the application knows a property by, resolved from the name a human uses.
  //
  // There is no property lookup endpoint — the New Building form carries every property
  // the signed-in user may post to as the options of its PropertyID select, so the form
  // that needs the id is also what publishes it. Returns '' when the property is not on
  // the account, which the caller asserts on rather than posting an empty id.
  async getPropertyId(propertyName: string): Promise<string> {
    const formResponse = await this.request.get('/Buildings/New', { headers: AJAX_HEADERS })

    return optionValueByText(await formResponse.text(), 'PropertyID', propertyName)
  }

  // Saves one building against `propertyId` and returns the name it generated.
  //
  // The endpoint takes the New Building form's own body: the property it is saving
  // against, then one grid row keyed by a guid the browser generates per row. Both the
  // `Buildings.index` marker and the `Buildings[<guid>].<field>` keys are how ASP.NET MVC
  // binds a collection, so the guid is arbitrary but must be the same in every key of the
  // row. Address.AddressID is posted empty: the row is new, so the application assigns it.
  async addBuilding(
    propertyId: string,
    propertyName: string,
    building: BuildingApiData,
  ): Promise<CreatedBuilding> {
    const name = `${building.namePrefix}${Math.random().toString(36).slice(2, 8)}`
    const rowKey = randomUUID()

    const saveResponse = await this.request.post('/Buildings/New', {
      headers: AJAX_HEADERS,
      form: {
        PropertyID: propertyId,
        PropertyName: propertyName,
        'Buildings.index': rowKey,
        [`Buildings[${rowKey}].Name`]: name,
        [`Buildings[${rowKey}].Floors`]: building.floors,
        [`Buildings[${rowKey}].Description`]: building.description,
        [`Buildings[${rowKey}].Address.StreetAddress`]: building.streetAddress,
        [`Buildings[${rowKey}].Address.AddressID`]: '',
        [`Buildings[${rowKey}].Address.City`]: building.city,
        [`Buildings[${rowKey}].Address.State`]: building.province,
        [`Buildings[${rowKey}].Address.Zip`]: building.postalCode,
      },
    })

    return { name, saveResponse }
  }

  // Whether the application considers `name` taken on this property.
  //
  // This is the duplicate check the New Building form runs before it saves, so it answers
  // from the same rule the save enforces: {"empty":true} while the name is free, and the
  // duplicate-name message once a building holds it. It is read as "taken" only on that
  // message — an error payload is neither shape, and must not read as proof the building
  // exists.
  async isBuildingNameTaken(propertyId: string, name: string): Promise<boolean> {
    const existsResponse = await this.request.get('/Buildings/BuildingExists', {
      headers: AJAX_HEADERS,
      params: { propertyID: propertyId, name },
    })
    const body = await existsResponse.json()

    return body.message === 'This building already exists'
  }

  // The building the list shows for `name`, or undefined when the property lists no such
  // building — which the caller asserts on.
  //
  // Rows are matched on the name cell alone, and on the whole value: a name that only
  // appears in another building's Description, or a generated name that is the prefix of
  // a longer one, must not satisfy the caller's assertion. Returning the row's other
  // cells is what lets the spec check the application stored what the save sent, rather
  // than only that something with the right name exists.
  async getBuildingFromList(propertyId: string, name: string): Promise<ListedBuilding | undefined> {
    const listResponse = await this.request.get('/Buildings/IndexPageBuildingList', {
      headers: AJAX_HEADERS,
      params: { propertyID: propertyId, page: ALL_PAGES },
    })
    const listHtml = await listResponse.text()

    for (const row of listHtml.matchAll(/<tr class="building">([\s\S]*?)<\/tr>/g)) {
      const listedBuilding = {
        name: cellText(row[1], 'bl-name-col'),
        floors: cellText(row[1], 'bl-floors-col'),
        description: cellText(row[1], 'bl-description-col'),
      }

      if (listedBuilding.name === name) {
        return listedBuilding
      }
    }

    return undefined
  }
}
